"""The persisted shape of a booking.

Both halves of the brief's persistence requirement live on one row: ``raw_input``
is exactly what the production office typed, and ``parsed_request`` / ``quote``
are the structured output the API returned for it.

The quote is stored as a document rather than recomputed on read. A quote is a
historical record -- if the rate card changes next month, an existing booking
must still read back at the price it was confirmed at.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import JSON, DateTime, Integer, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: JSONB where it exists, plain JSON on SQLite.
JsonDocument = JSON().with_variant(JSONB(), "postgresql")


class Base(DeclarativeBase):
    pass


class BookingRecord(Base):
    __tablename__ = "accommodation_bookings"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)
    #: Sequential bill number. Unique so two racing writers cannot share one;
    #: the loser retries rather than issuing a duplicate reference.
    bill_number: Mapped[int] = mapped_column(Integer)

    raw_input: Mapped[str] = mapped_column(Text)
    parsed_request: Mapped[dict[str, Any]] = mapped_column(JsonDocument)
    quote: Mapped[dict[str, Any]] = mapped_column(JsonDocument)

    # Denormalised from the quote so the list endpoint can sort and summarise
    # without opening every JSON document.
    currency: Mapped[str] = mapped_column(String(3))
    #: Minor units (cents). Integers are exact on every backend; the JSON quote
    #: remains the authoritative, human-readable record.
    total_cents: Mapped[int] = mapped_column(Integer)
    nights: Mapped[int] = mapped_column(Integer)
    guests: Mapped[int] = mapped_column(Integer)
    room_count: Mapped[int] = mapped_column(Integer)
    meal_plan: Mapped[str] = mapped_column(String(16), index=True)

    # Named explicitly: an unnamed constraint gets a different autogenerated
    # name on every backend, which makes it unreferenceable from a migration.
    __table_args__ = (UniqueConstraint("bill_number", name="uq_bookings_bill_number"),)
